# SHub - By DirolGaming

# This is the section where the plugin saves Hub location info automatically. You can manually change these values, but do it only if you know what you are doing.
# These values will be automatically updated when an admin executes the /sethub command.
world:
  name: 'world'
  X:
  Y:
  Z:
  Yaw:
  Pitch:
  usespawnpointinstead: "true"

# Teleport on join - Select if you want to teleport players directly to hub when they join.
teleport-on-join: true

# Doublejump settings
velocity: 1.5
enable-doublejump: true
enable-doublejump-Messages: true
doublejump-message: '&7Woosh!'
doublejump-cooldownleft: '&7You must wait &c&l%time% &7seconds to doublejump again'
doublejump-cooldownmessage: '&7You can now use the doublejump function again!'
effect-enable: true
#Effect, effects have a BUKKIT Effect name. The plugin will capitalize the Effect names. To see available effects go here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
#Be careful with it, because it can cause problems when you accidentaly insert a Sound Effect, not a Particle Effect
#This is the doublejump effect
effect: 'MOBSPAWNER_FLAMES'
#SHub chat toggle messages
chat-unmute: "&7Chat has been unmuted!"
chat-mute: "&7Chat has been muted!"

# Hub gun sounds and effects section
# These use basically the same format as the Doublejump effect, but with these you have more control over the sounds and effects.
# For example: ENTITY_CAT_AMBIENT:10:1 means that the sound is ENTITY_CAT_AMBIENT, the speed of it is 10 and the pitch of it is 1 changing the speed and the pitch of sounds and effects is entirely up to you.
# For available Sounds and Effects visit these sites:
# Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
enable-sound: true
sounds:
  - "ENTITY_CAT_AMBIENT:10:1"
  - "ENTITY_WOLF_AMBIENT:10:1"
  - "ENTITY_ENDER_DRAGON_FLAP:10:1"
  - "BLOCK_WATER_AMBIENT:10:1"
enable-effect: true
effects:
  - "MOBSPAWNER_FLAMES:5"
  - "MOBSPAWNER_FLAMES:5"
  - "MOBSPAWNER_FLAMES:5"
  - "ENDER_SIGNAL:5"

# Plugin update checker and notifier.
check-update: true
notify-update: true
enable-notifications: '&c&lSafeHub &7update notifications are now &a&lenabled&7!'
disable-notifications: '&c&lSafeHub &7update notifications are now &c&ldisabled&7!'


# items - items must have a BUKKIT Material name, otherwise they won't work. The plugin will capitalize the item names, so don't worry about that
# If you want to make a great server selector, use ItemCommands & ChestCommandsGUI plugins to make an awesome looking server selector
# If you do not want to use all of the customizable 9 items, you can disable them one at a time by changing their name to "-"
# Example:
# item-x:
#   item: "-"
item-1:
  item: compass
  name: '&c&lServer selector'
  lore: '&7Insert text here'
  slot: 1

item-2:
  item: BLAZE_ROD
  name: '&c&lHub Gun'
  lore: '&7Insert text here, or leave it empty.'
  slot: 2

item-3:
  item: diamond
  name: '&c&lA fine looking diamond'
  lore: ''
  slot: 3

item-4:
  item: clock
  name: '&c&lMagic Clock'
  lore: '&7Hide/Show players'
  slot: 4

item-5:
  item: "-"
  name: '&c&lThis is string.'
  lore: ''
  slot: 5

item-6:
  item: "-"
  name: '&c&lShine bright like a emerald'
  lore: '&7Insert text here'
  slot: 6

item-7:
  item: "-"
  name: '&c&lbook'
  lore: '&7Be smart, read'
  slot: 7

item-8:
  item: "-"
  name: '&c&lStone is a stone'
  lore: '&7Insert text here'
  slot: 8

item-9:
  item: "-"
  name: '&c&lfoo'
  lore: '&7bedrock oo'
  slot: 9

#Change the join and leave messages! Use the %player% if you want to display the player's name
enable-join-quit-messages: true
join-message: '&c&l%player% &7has joined the server!'
quit-message: '&c&l%player% &7has left the server!'

#Basic implementation of disabling time
lock-time: false
time: 5600

#Some common messages of SHub
no-permission: '&cYou do not have enough permissions for that command!'
unknown-command: '&7Unknown command, use /hub to see available commands.'
reload-message: '&8[&c&lSHub&8] &7plugin has been reloaded.'
on-teleport-to-spawn: '&7You have been teleported to &c&lHub&7.'
set-hub: '&7New &c&lHub &7location has been set.'

#Select if you want to allow item-drops and inventory-interaction. Inventory-interaction will only affect those players who are on Survival/Adventure gamemodes
item-drop: false
inventory-interaction: false

#MOTD - Message Of The Day
motd:
  enable: true
  motd: "&7Welcome to this server!"
  enable-hover: true
  motd-hover: "&7Click on this text to open a URL!"
  enable-click: true
  click-url: "www.sitanikerdis.ee"

#Do you want to clear player's inventories when they leave/join the server? Items what are spawned by SHub will not be affected by this
#I recommend leaving this to false when using this plugin in a per-world server
clear-on-quit: false
clear-on-join: false

#Would you like to deny players placing down blocks (leave it to false, if you do not want the plugin to deny players from placing blocks or you have another plugin handling this)
on-place-block-deny: true
block-place-denymsg: "&7Block placing has been deactivated in the SHub config."

#Boolean values (they can only be true or false)
gamemode-on-join-adventure: true
disable-fall-damage: true
disable-hunger: true
disable-weather: true

#Magic-Clock Messages.
hide-players-message: '&8[&c&lSHub&8] &7All players have been hidden!'
show-players-message: '&8[&c&lSHub&8] &7All players are now visible!'

#Movement - Teleport player back to spawn if he falls (leave this off, if you do not have a hub that is in the air, and players have the danger of falling into void).
#Movement - cordinate-y only accepts integers (otherwise known as numbers). Example: Hub is at Y 89, player falls, if the cordinate-y is 60 then when the player's at Y=60, he will be teleported back to spawn.
enable-movementYtp: false
cordinate-y: 15

#Thank you for downloading this plugin, if you like this plugin or have any feedback, please post it in the review section on the Plugin Spigot page.
#If you have found a bug, please PM me, or post it in the Discussion section of the Plugin Spigot page

#DO NOT TOUCH THIS
config-ver: 3.0.1